coverage logic rewrite

diff --git a/tools/pipelines/templates/build-npm-package.yml b/tools/pipelines/templates/build-npm-package.yml
--- a/tools/pipelines/templates/build-npm-package.yml
+++ b/tools/pipelines/templates/build-npm-package.yml
@@ -32,6 +32,11 @@ parameters:
   default:
   - { name: "ci:test", jobName: "CiTest" }
 
+- name: coverageTests
+  type: object
+  default:
+  - { name: "ci:test", jobName: "CiTest" }
+
 # A list of directories (under the buildDirectory) to run the PublishTestResults task on in separate steps.
 # Used to avoid the force merge limit of 100 result files.
 - name: testResultDirs
@@ -568,6 +573,144 @@ extends:
                       sbomEnabled: false
                       publishLocation: pipeline
 
+          - job: Coverage tests
+            displayName: "Coverage tests"
+            dependsOn: build
+            variables:
+              - group: ado-feeds
+              - group: storage-vars
+              - name: releaseBuildVar
+                value: '$[variables.releaseBuild]'
+              - ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
+                - name: targetBranchName
+                  value: $(System.PullRequest.TargetBranch)
+              # Absolute path to the folder that contains the source code for the telemetry-generator package, which is
+              # used in a few places in the pipeline to push custom telemetry to Kusto.
+              - name: absolutePathToTelemetryGenerator
+                value: $(Build.SourcesDirectory)/tools/telemetry-generator
+                readonly: true
+            steps:
+              # Setup
+              - checkout: none
+
+              - task: DownloadPipelineArtifact@2
+                inputs:
+                  artifact: buildOutput
+                  targetPath: '${{ parameters.buildDirectory }}'
+
+              - template: /tools/pipelines/templates/include-use-node-version.yml@self
+
+              - template: /tools/pipelines/templates/include-install.yml@self
+                parameters:
+                  packageManager: '${{ parameters.packageManager }}'
+                  buildDirectory: '${{ parameters.buildDirectory }}'
+                  packageManagerInstallCommand: 'pnpm install --no-frozen-lockfile'
+
+              # Set variable startTest if the build succeed so that we can run all the test tasks whether they are failed or not
+              - script: |
+                  echo "##vso[task.setvariable variable=startTest]true"
+                displayName: Start Test
+
+              - ${{ each test in parameters.coverageTests }}:
+                - template: /tools/pipelines/templates/include-test-task.yml@self
+                  parameters:
+                    taskTestStep: '${{ test.name }}:coverage'
+                    buildDirectory: '${{ parameters.buildDirectory }}'
+
+              - task: Npm@1
+                displayName: 'npm run test:copyresults'
+                inputs:
+                  command: custom
+                  workingDir: '${{ parameters.buildDirectory }}'
+                  customCommand: 'run test:copyresults'
+
+              # Test - Upload coverage results
+              # Some webpacked file using externals introduce file name with quotes in them
+              # and Istanbul's cobertura reporter doesn't escape them causing parse error when we publish
+              # A quick fix to patch the file with sed. (See https://github.com/bcoe/c8/issues/302)
+              - template: /tools/pipelines/templates/include-install-build-tools.yml@self
+                parameters:
+                  buildDirectory: ${{ parameters.buildDirectory }}
+                  buildToolsVersionToInstall: repo
+                  pnpmStorePath: $(Pipeline.Workspace)/.pnpm-store
+
+              - task: Bash@3
+                displayName: Check for nyc/report directory
+                condition: and(succeededOrFailed(), eq(variables['startTest'], 'true'))
+                inputs:
+                  targetType: 'inline'
+                  workingDirectory: '${{ parameters.buildDirectory }}'
+                  script: |
+                    set -eu -o pipefail
+                    test -d nyc/report && echo '##vso[task.setvariable variable=ReportDirExists;]true' || echo 'No nyc/report directory'
+
+              - task: Bash@3
+                displayName: Patch Coverage Results
+                condition: and(succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
+                inputs:
+                  targetType: 'inline'
+                  workingDirectory: '${{ parameters.buildDirectory }}/nyc/report'
+                  script: |
+                    set -eu -o pipefail
+                    sed -e 's/\(filename=\".*[\\/]external .*\)"\(.*\)""/\1\&quot;\2\&quot;"/' cobertura-coverage.xml > cobertura-coverage-patched.xml
+
+              - task: PublishCodeCoverageResults@2
+                displayName: Publish Code Coverage
+                condition: and(succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
+                inputs:
+                  summaryFileLocation: ${{ parameters.buildDirectory }}/nyc/report/cobertura-coverage-patched.xml
+                  failIfCoverageEmpty: true
+              - task: CopyFiles@2
+                displayName: Copy code coverage report to artifact staging directory
+                condition: and(succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
+                inputs:
+                  sourceFolder: '${{ parameters.buildDirectory }}/nyc/report'
+                  targetFolder: $(Build.ArtifactStagingDirectory)/codeCoverageAnalysis
+              - task: Bash@3
+                displayName: Report Code Coverage Comparison
+                condition: and(succeededOrFailed(), eq('${{ parameters.reportCodeCoverageComparison }}', true), eq(variables['ReportDirExists'], 'true'), eq(variables['System.PullRequest.TargetBranch'], 'main'))
+                continueOnError: false
+                env:
+                  ADO_API_TOKEN: '$(System.AccessToken)'
+                  GITHUB_API_TOKEN: '$(githubPublicRepoSecret)'
+                  TARGET_BRANCH_NAME: '$(targetBranchName)'
+                  ADO_BUILD_ID: '$(Build.BuildId)'
+                  GITHUB_PR_NUMBER: '$(System.PullRequest.PullRequestNumber)'
+                  GITHUB_REPOSITORY_NAME: '$(Build.Repository.Name)'
+                  ADO_CI_BUILD_DEFINITION_ID_BASELINE: 48
+                  ADO_CI_BUILD_DEFINITION_ID_PR: 11
+                inputs:
+                  targetType: inline
+                  workingDirectory: '${{ parameters.buildDirectory }}'
+                  script: |
+                    set -eu -o pipefail
+                    echo "Github Repository Name: $GITHUB_REPOSITORY_NAME"
+                    echo "Github PR number: $GITHUB_PR_NUMBER"
+                    echo "ADO Build Number: $ADO_BUILD_ID"
+                    echo "Target Branch Name: $TARGET_BRANCH_NAME"
+                    echo "ADO CI BUILD_DEFINITION_ID for baseline: $ADO_CI_BUILD_DEFINITION_ID_BASELINE"
+                    echo "ADO CI BUILD_DEFINITION_ID for PR: $ADO_CI_BUILD_DEFINITION_ID_PR"
+                    echo "Running code coverage comparison"
+                    flub report codeCoverage --verbose
+
+            # Process test result, include publishing and logging
+              - template: /tools/pipelines/templates/include-process-test-results.yml@self
+                parameters:
+                  buildDirectory: '${{ parameters.buildDirectory }}'
+                  testResultDirs: '${{ parameters.testResultDirs }}'
+
+            templateContext:
+              outputParentDirectory: $(Build.ArtifactStagingDirectory)/codeCoverageAnalysis
+              outputs:
+                - ${{ if eq(parameters.testCoverage, true) }}:
+                      - output: pipelineArtifact
+                        displayName: Publish Artifacts - code-coverage
+                        condition: and( succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
+                        targetPath: $(Build.ArtifactStagingDirectory)/codeCoverageAnalysis
+                        artifactName: '${{ test.jobName }}-$(System.JobAttempt)'
+                        sbomEnabled: false
+                        publishLocation: pipeline
+
           # Job - Tests
           - ${{ each test in parameters.taskTest }}:
             - job: Test_${{ test.jobName }}
@@ -610,25 +753,10 @@ extends:
                     echo "##vso[task.setvariable variable=startTest]true"
                   displayName: Start Test
 
-                - script: |
-                    echo "Running ${{ test.name }}test"
-                    if [[ "${{ parameters.testCoverage }}" == "true" ]]; then
-                      if [[ "${{ test.name }}" == "ci:test:mocha" || "${{ test.name }}" == "ci:test:realsvc:local" ]]; then
-                        echo "Running test with coverage"
-                        echo "##vso[task.setvariable variable=runWithCoverage]true"
-                        return 0
-                      fi
-                    fi
-                    echo "Running test without coverage"
-                    echo "##vso[task.setvariable variable=runWithCoverage]false"
-                  displayName: 'runWithCoverage variable'
-
                 - template: /tools/pipelines/templates/include-test-task.yml@self
                   parameters:
                     taskTestStep: '${{ test.name }}'
                     buildDirectory: '${{ parameters.buildDirectory }}'
-                    # Don't run with coverage if the task is a PR and the task is a tinylicious service and stress test. We don't include coverage for these tests in our baseline coverage stats, so we don't need to run them with coverage here too.
-                    testCoverage: ${{and(parameters.testCoverage,ne(variables['Build.Reason'], 'PullRequest'))}}
 
                 - task: Npm@1
                   displayName: 'npm run test:copyresults'
@@ -657,94 +785,11 @@ extends:
                   # At this point we want to publish the tinylicious.log artifact, but as part of 1ES migration
                   # that is now part of templateContext.outputs below.
 
-                # Test - Upload coverage results
-                # Some webpacked file using externals introduce file name with quotes in them
-                # and Istanbul's cobertura reporter doesn't escape them causing parse error when we publish
-                # A quick fix to patch the file with sed. (See https://github.com/bcoe/c8/issues/302)
-                - ${{ if variables['runWithCoverage'] }}:
-                    - template: /tools/pipelines/templates/include-install-build-tools.yml@self
-                      parameters:
-                        buildDirectory: ${{ parameters.buildDirectory }}
-                        buildToolsVersionToInstall: repo
-                        pnpmStorePath: $(Pipeline.Workspace)/.pnpm-store
-
-                    - task: Bash@3
-                      displayName: Check for nyc/report directory
-                      condition: and(succeededOrFailed(), eq(variables['startTest'], 'true'))
-                      inputs:
-                        targetType: 'inline'
-                        workingDirectory: '${{ parameters.buildDirectory }}'
-                        script: |
-                          set -eu -o pipefail
-                          test -d nyc/report && echo '##vso[task.setvariable variable=ReportDirExists;]true' || echo 'No nyc/report directory'
-
-                    - task: Bash@3
-                      displayName: Patch Coverage Results
-                      condition: and(succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
-                      inputs:
-                        targetType: 'inline'
-                        workingDirectory: '${{ parameters.buildDirectory }}/nyc/report'
-                        script: |
-                          set -eu -o pipefail
-                          sed -e 's/\(filename=\".*[\\/]external .*\)"\(.*\)""/\1\&quot;\2\&quot;"/' cobertura-coverage.xml > cobertura-coverage-patched.xml
-
-                    - task: PublishCodeCoverageResults@2
-                      displayName: Publish Code Coverage
-                      condition: and(succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
-                      inputs:
-                        summaryFileLocation: ${{ parameters.buildDirectory }}/nyc/report/cobertura-coverage-patched.xml
-                        failIfCoverageEmpty: true
-                    - task: CopyFiles@2
-                      displayName: Copy code coverage report to artifact staging directory
-                      condition: and(succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
-                      inputs:
-                        sourceFolder: '${{ parameters.buildDirectory }}/nyc/report'
-                        targetFolder: $(Build.ArtifactStagingDirectory)/codeCoverageAnalysis
-                    - task: Bash@3
-                      displayName: Report Code Coverage Comparison
-                      condition: and(succeededOrFailed(), eq('${{ parameters.reportCodeCoverageComparison }}', true), eq(variables['ReportDirExists'], 'true'), eq(variables['System.PullRequest.TargetBranch'], 'main'))
-                      continueOnError: false
-                      env:
-                        ADO_API_TOKEN: '$(System.AccessToken)'
-                        GITHUB_API_TOKEN: '$(githubPublicRepoSecret)'
-                        TARGET_BRANCH_NAME: '$(targetBranchName)'
-                        ADO_BUILD_ID: '$(Build.BuildId)'
-                        GITHUB_PR_NUMBER: '$(System.PullRequest.PullRequestNumber)'
-                        GITHUB_REPOSITORY_NAME: '$(Build.Repository.Name)'
-                        ADO_CI_BUILD_DEFINITION_ID_BASELINE: 48
-                        ADO_CI_BUILD_DEFINITION_ID_PR: 11
-                      inputs:
-                        targetType: inline
-                        workingDirectory: '${{ parameters.buildDirectory }}'
-                        script: |
-                          set -eu -o pipefail
-                          echo "Github Repository Name: $GITHUB_REPOSITORY_NAME"
-                          echo "Github PR number: $GITHUB_PR_NUMBER"
-                          echo "ADO Build Number: $ADO_BUILD_ID"
-                          echo "Target Branch Name: $TARGET_BRANCH_NAME"
-                          echo "ADO CI BUILD_DEFINITION_ID for baseline: $ADO_CI_BUILD_DEFINITION_ID_BASELINE"
-                          echo "ADO CI BUILD_DEFINITION_ID for PR: $ADO_CI_BUILD_DEFINITION_ID_PR"
-                          echo "Running code coverage comparison"
-                          flub report codeCoverage --verbose
-
-
                 # Process test result, include publishing and logging
                 - template: /tools/pipelines/templates/include-process-test-results.yml@self
                   parameters:
                     buildDirectory: '${{ parameters.buildDirectory }}'
                     testResultDirs: '${{ parameters.testResultDirs }}'
-
-              templateContext:
-                outputParentDirectory: $(Build.ArtifactStagingDirectory)/codeCoverageAnalysis
-                outputs:
-                  - ${{ if eq(parameters.testCoverage, true) }}:
-                        - output: pipelineArtifact
-                          displayName: Publish Artifacts - code-coverage
-                          condition: and( succeededOrFailed(), eq(variables['ReportDirExists'], 'true'))
-                          targetPath: $(Build.ArtifactStagingDirectory)/codeCoverageAnalysis
-                          artifactName: '${{ test.jobName }}-$(System.JobAttempt)'
-                          sbomEnabled: false
-                          publishLocation: pipeline
 
       # Publish stage
       - ${{ if eq(parameters.publish, true) }}:
