parser script, build-npm-package test parse step

diff --git a/tools/pipelines/templates/build-npm-package.yml b/tools/pipelines/templates/build-npm-package.yml
--- a/tools/pipelines/templates/build-npm-package.yml
+++ b/tools/pipelines/templates/build-npm-package.yml
@@ -360,6 +360,46 @@ stages:
               mergeTestResults: false
             condition: and(succeededOrFailed(), eq(variables['startTest'], 'true'))
 
+          # Check Published Tests
+          - task: Bash@3
+            displayName: 'Check for nyc directory'
+            inputs:
+              targetType: 'inline'
+              workingDirectory: ${{ parameters.buildDirectory }}
+              script: |
+                test -d nyc && echo '##vso[task.setvariable variable=TestReportsExists;]true' || echo 'No nyc directory'
+            condition: and(succeededOrFailed(), eq(variables['startTest'], 'true'))
+
+          # Copy Test Reports
+          - task: CopyFiles@2
+            displayName: Copy Test Reports JSON
+            inputs:
+              SourceFolder: ${{ parameters.buildDirectory }}/nyc
+              Contents: '**/*junit-report.json'
+              TargetFolder: '$(Build.ArtifactStagingDirectory)/testFiles'
+            condition: and(succeededOrFailed(), eq(variables['TestReportsExists'], 'true'))
+
+          # Console Log Failed Tests
+          - task: Bash@3
+            displayName: Log Failed Tests
+            inputs:
+              targetType: inline
+              script: |
+                failedTests=$(node report-parser.js '$(Build.ArtifactStagingDirectory)/testFiles')
+                if [ $failedTests == [] ]
+                then
+                  echo "No failed tests."
+                else
+                  echo "##[error] $failedTests"
+                fi
+              workingDirectory: tools/report-parser
+            condition: and(succeededOrFailed(), eq(variables['TestReportsExists'], 'true'))
+
+
+
+
+
+
         # Pack
         - ${{ if ne(parameters.taskPack, false) }}:
           - task: Bash@3
