Replace `set -eux` with `set -eu`

diff --git a/tools/pipelines/templates/build-docker-service.yml b/tools/pipelines/templates/build-docker-service.yml
--- a/tools/pipelines/templates/build-docker-service.yml
+++ b/tools/pipelines/templates/build-docker-service.yml
@@ -187,7 +187,7 @@ extends:
             targetType: 'inline'
             workingDirectory: ${{ parameters.buildDirectory }}
             script: |
-              # Note: deliberately not using `set -eux -o pipefail` because this script leverages the return code of grep
+              # Note: deliberately not using `set -eu -o pipefail` because this script leverages the return code of grep
               # even in an error case
 
               # Show all task group conditions
@@ -290,7 +290,7 @@ extends:
               targetType: 'inline'
               workingDirectory: ${{ parameters.buildDirectory }}
               script: |
-                set -eux -o pipefail
+                set -eu -o pipefail
                 ${{ parameters.packageManagerInstallCommand }}
 
           - template: /tools/pipelines/templates/include-set-package-version.yml@self
@@ -307,7 +307,7 @@ extends:
             inputs:
               targetType: 'inline'
               script: |
-                set -eux -o pipefail
+                set -eu -o pipefail
                 echo "$(containerTagSuffix)"
                 echo "##vso[task.setvariable variable=version;isOutput=true]$(containerTagSuffix)"
 
@@ -321,7 +321,7 @@ extends:
             targetType: 'inline'
             workingDirectory: $(Build.SourcesDirectory)
             script: |
-              set -eux -o pipefail
+              set -eu -o pipefail
               cp ./CredScanSuppressions.json ${{ parameters.buildDirectory }}
 
         # The GitSSH Dockerfile does not have a 'base' target nor does it run pack/lint/test/docs tasks, so skip
@@ -351,7 +351,7 @@ extends:
               inputs:
                 targetType: 'inline'
                 script: |
-                  set -eux -o pipefail
+                  set -eu -o pipefail
                   mkdir -p $(hostPathToPackArtifact)
                   mkdir -p $(hostPathToTestResultsArtifact)
 
@@ -377,7 +377,7 @@ extends:
                 targetType: 'inline'
                 workingDirectory: ${{ parameters.buildDirectory }}
                 script: |
-                  set -eux -o pipefail
+                  set -eu -o pipefail
                   flub list --no-private $RELEASE_GROUP --tarball --feed public --outFile $STAGING_PATH/pack/packagePublishOrder-public.txt
                   flub list --no-private $RELEASE_GROUP --tarball --feed internal-build --outFile $STAGING_PATH/pack/packagePublishOrder-internal-build.txt
                   flub list --no-private $RELEASE_GROUP --tarball --feed internal-dev --outFile $STAGING_PATH/pack/packagePublishOrder-internal-dev.txt
@@ -449,7 +449,7 @@ extends:
                 targetType: 'inline'
                 workingDirectory: $(hostPathToTestResultsArtifact)
                 script: |
-                  set -eux -o pipefail
+                  set -eu -o pipefail
                   sudo chmod -R +r .
 
           # Docs
@@ -494,7 +494,7 @@ extends:
               targetType: 'inline'
               workingDirectory: ${{ parameters.buildDirectory }}
               script: |
-                set -eux -o pipefail
+                set -eu -o pipefail
                 # containerTag should always be pushed
                 FINAL_TAG_LIST=$(containerTag)
 
@@ -520,7 +520,7 @@ extends:
               targetType: 'inline'
               workingDirectory: ${{ parameters.buildDirectory }}
               script: |
-                set -eux -o pipefail
+                set -eu -o pipefail
                 pnpm store prune
 
         templateContext:
diff --git a/tools/pipelines/templates/include-set-package-version.yml b/tools/pipelines/templates/include-set-package-version.yml
--- a/tools/pipelines/templates/include-set-package-version.yml
+++ b/tools/pipelines/templates/include-set-package-version.yml
@@ -56,7 +56,7 @@ steps:
     targetType: 'inline'
     workingDirectory: ${{ parameters.buildDirectory }}
     script: |
-      set -eux -o pipefail
+      set -eu -o pipefail
       # expect lerna.json and package.json be in the current working directory
 
       echo VERSION_BUILDNUMBER=$VERSION_BUILDNUMBER
@@ -79,7 +79,7 @@ steps:
       targetType: 'inline'
       workingDirectory: ${{ parameters.buildDirectory }}
       script: |
-        set -eux -o pipefail
+        set -eu -o pipefail
         # At this point in the pipeline the build hasn't been done, so we skip checking if the types files and other build outputs exist.
         flub release setPackageTypesField -g ${{ parameters.tagName }} --types ${{ parameters.packageTypesOverride }} --no-checkFileExists
 
@@ -102,7 +102,7 @@ steps:
     targetType: 'inline'
     workingDirectory: ${{ parameters.buildDirectory }}
     script: |
-      # Note: deliberately not using `set -eux -o pipefail` because this script leverages the return code of grep
+      # Note: deliberately not using `set -eu -o pipefail` because this script leverages the return code of grep
       # even in an error case
       grep -r -e "\^2.0.0-internal.\d*.\d*.\d*" `find . -type d -name node_modules -prune -o -name 'package.json' -print`
       if [[ $? == 0 ]]; then
@@ -118,7 +118,7 @@ steps:
     targetType: 'inline'
     workingDirectory: ${{ parameters.buildDirectory }}
     script: |
-      # Note: deliberately not using `set -eux -o pipefail` because this script leverages the return code of grep
+      # Note: deliberately not using `set -eu -o pipefail` because this script leverages the return code of grep
       # even in an error case
       grep -r -e "\^2.0.0-dev.\d*.\d*.\d*.\d*" `find . -type d -name node_modules -prune -o -name 'package.json' -print`
       if [[ $? == 0 ]]; then
