Restore initialize step, remove unnecessary parts

diff --git a/tools/pipelines/templates/include-test-real-service.yml b/tools/pipelines/templates/include-test-real-service.yml
--- a/tools/pipelines/templates/include-test-real-service.yml
+++ b/tools/pipelines/templates/include-test-real-service.yml
@@ -240,6 +240,21 @@ stages:
             # - buildId: <the id of the triggering build>
             # preferTriggeringPipeline: true
 
+        - task: Bash@3
+          name: Initialize
+          displayName: Initialize
+          inputs:
+            targetType: 'inline'
+            workingDirectory: ${{ parameters.testWorkspace }}
+            script: |
+              set -eu -o pipefail
+              if [[ `ls -1 ${{ variables.testPackagePathPattern }} | wc -l` -eq 1 ]]; then
+                echo "##vso[task.setvariable variable=testPackageTgz;isOutput=true]`ls ${{ variables.testPackagePathPattern }}`"
+              else
+                ls -1 ${{ variables.testPackagePathPattern }}
+                echo "##vso[task.logissue type=error]Test package '${{ parameters.testPackage }}' not found, or there are more than one found"
+                exit -1
+              fi
         # Install test package
         - task: Bash@3
           displayName: 'pnpm install'
