rerun publish steps when network error

diff --git a/tools/pipelines/templates/include-publish-npm-package-steps.yml b/tools/pipelines/templates/include-publish-npm-package-steps.yml
--- a/tools/pipelines/templates/include-publish-npm-package-steps.yml
+++ b/tools/pipelines/templates/include-publish-npm-package-steps.yml
@@ -86,7 +86,6 @@ steps:
       fi
       echo Tag: $tag
       cp .npmrc ~/.npmrc
-      errorFlag=0
       maximumRetryIfNetworkError=3
       if [[ -f $(Pipeline.Workspace)/pack/packagePublishOrder.txt ]]; then
         packages=$(cat $(Pipeline.Workspace)/pack/packagePublishOrder.txt)
@@ -107,64 +106,45 @@ steps:
           do
             npm publish $f $tag ${{ parameters.publishFlags }} 2>&1 | tee publish_log
 
-            checkError=$(npx npm-return-error-msg)
-
-            echo "CHECK ERROR : " $checkError
-
-            if [ "$checkError" == "npm ERR! code ENOTFOUND" ];
+            if grep -q "npm ERR!" "publish_log"
             then
-              echo "Check Error! After!"
-              if ! $i -eq $maximumRetryIfNetworkError
-              then
-                echo "Network Error Detected"
-                continue
-              else
-                echo "Final Network Error"
-                exit 1
-              fi
+                if grep -q "code ENOTFOUND" "publish_log"
+                then
+                  if ! $i -eq $maximumRetryIfNetworkError
+                  then
+                    echo "Network Error Detected"
+                    continue
+                  else
+                    echo "Final Network Error"
+                    exit 1
+                  fi
+                else
+                  if grep -q "You cannot publish over the previously published versions" "publish_log"
+                  then
+                    echo Package has already been published.
+                    local_f="${f}_local"
+                    mv "$f" "$local_f"
+                    package_name=$(grep -oP 'npm notice package: \K.*' "publish_log")
+                    npm pack $package_name
+                    if cmp -s "$f" "$local_f"
+                    then
+                      echo Continuing as published package matches the current one that was attempting to be released.
+                      continue
+                    else
+                      echo ERROR: Published package does not match the current one attempting to be released for the same version.
+                    fi
+                  fi
+                  rm "$f"
+                  mv "$local_f" "$f"
+                  exit 1
+                fi
+            else
+              rm publish_log
+              break
             fi
-
-            # if grep -q "npm ERR!" "publish_log"
-            # then
-            #     echo "Check ERROR MSG! AFTER"
-            #     if grep -q "code ENOTFOUND" "publish_log"
-            #     then
-            #       if ! $i -eq $maximumRetryIfNetworkError
-            #       then
-            #         echo "Network Error Detected"
-            #         continue
-            #       else
-            #         echo "Final Network Error"
-            #         exit 1
-            #       fi
-            #     else
-            #       if grep -q "You cannot publish over the previously published versions" "publish_log"
-            #       then
-            #         echo Package has already been published.
-            #         local_f="${f}_local"
-            #         mv "$f" "$local_f"
-            #         package_name=$(grep -oP 'npm notice package: \K.*' "publish_log")
-            #         npm pack $package_name
-            #         if cmp -s "$f" "$local_f"
-            #         then
-            #           echo Continuing as published package matches the current one that was attempting to be released.
-            #           continue
-            #         else
-            #           echo ERROR: Published package does not match the current one attempting to be released for the same version.
-            #         fi
-            #       fi
-            #       rm "$f"
-            #       mv "$local_f" "$f"
-            #       exit 1
-            #     fi
-            # else
-            #   rm publish_log
-            #   break
-            # fi
-            # rm publish_log
+            rm publish_log
           done
         fi
-        let errorFlag+=1
       done
       rm ~/.npmrc
       exit 1
