add pipeline steps to include-test-real-service

diff --git a/tools/pipelines/templates/include-test-real-service.yml b/tools/pipelines/templates/include-test-real-service.yml
--- a/tools/pipelines/templates/include-test-real-service.yml
+++ b/tools/pipelines/templates/include-test-real-service.yml
@@ -346,4 +346,30 @@ jobs:
           mergeTestResults: false
         condition: succeededOrFailed()
 
+      # Check Published Tests
+      - task: Bash@3
+        displayName: 'Check for nyc directory'
+        inputs:
+          targetType: 'inline'
+          workingDirectory: ${{ parameters.buildDirectory }}
+          script: |
+            test -d nyc && echo '##vso[task.setvariable variable=TestReportsExists;]true' || echo 'No nyc directory'
+        condition: and(succeededOrFailed(), eq(variables['startTest'], 'true'))
+
+      # Console Log Failed Tests
+      - task: Bash@3
+        displayName: Log Failed Tests
+        inputs:
+          targetType: inline
+          script: |
+            failedTests=$(node report-parser.js '$(variables.testPackageDir)/testFiles')
+            if [ $failedTests == [] ]
+            then
+              echo "No failed tests."
+            else
+              echo "##[error] $failedTests"
+            fi
+          workingDirectory: tools/report-parser
+        condition: and(succeededOrFailed(), eq(variables['TestReportsExists'], 'true'))
+
       - ${{ parameters.additionalSteps }}
