add conditions

diff --git a/tools/pipelines/templates/include-publish-npm-package-steps.yml b/tools/pipelines/templates/include-publish-npm-package-steps.yml
--- a/tools/pipelines/templates/include-publish-npm-package-steps.yml
+++ b/tools/pipelines/templates/include-publish-npm-package-steps.yml
@@ -99,51 +99,43 @@ steps:
           checkVersion=${f##/*}
           checkVersion=${checkVersion:2:-4}
 
-          echo "CheckVersion 0 :" $checkVersion
-
           if [[ $checkVersion == *"fluidframework"* ]]; then
             checkVersion=$(echo $checkVersion | sed 's/-/\/''/1')
           else
             checkVersion=$(echo $checkVersion | sed 's/-/\/''/2')
           fi
 
-          echo "CheckVersion Value I :" $checkVersion
           checkVersion=@$(echo $checkVersion | sed -E 's/-([0-9])/@\1/')
 
-          echo "CheckVersion Value II : " $checkVersion
+          checkError=$(npm view $checkVersion)
 
-          npm view $checkVersion
-
-          echo "-----------------------------------1"
-
-          npm view @fluidframework/tinylicious-client@0.0.0-96564-test
-
-          echo "-----------------------------------2"
-
-          npm publish $f $tag ${{ parameters.publishFlags }} 2>&1 | tee publish_log
-          if grep -q "npm ERR!" "publish_log"
-          then
-              if ! grep -q "You cannot publish over the previously published versions" "publish_log"
-              then
-                let t1+=1
-              else
-                echo Package has already been published.
-                local_f="${f}_local"
-                mv "$f" "$local_f"
-                package_name=$(grep -oP 'npm notice package: \K.*' "publish_log")
-                npm pack $package_name
-                if cmp -s "$f" "$local_f"
+          if [ grep -q "npm ERR!" ] || [ !checkError]; then
+            echo "Passed"
+            npm publish $f $tag ${{ parameters.publishFlags }} 2>&1 | tee publish_log
+            if grep -q "npm ERR!" "publish_log"
+            then
+                if ! grep -q "You cannot publish over the previously published versions" "publish_log"
                 then
-                  echo Continuing as published package matches the current one that was attempting to be released.
-                else
-                  echo ERROR: Published package does not match the current one attempting to be released for the same version.
                   let t1+=1
+                else
+                  echo Package has already been published.
+                  local_f="${f}_local"
+                  mv "$f" "$local_f"
+                  package_name=$(grep -oP 'npm notice package: \K.*' "publish_log")
+                  npm pack $package_name
+                  if cmp -s "$f" "$local_f"
+                  then
+                    echo Continuing as published package matches the current one that was attempting to be released.
+                  else
+                    echo ERROR: Published package does not match the current one attempting to be released for the same version.
+                    let t1+=1
+                  fi
+                  rm "$f"
+                  mv "$local_f" "$f"
                 fi
-                rm "$f"
-                mv "$local_f" "$f"
-              fi
+            fi
+            rm publish_log
           fi
-          rm publish_log
         fi
       done
       rm ~/.npmrc
