redo changes

diff --git a/tools/pipelines/templates/include-publish-npm-package-steps.yml b/tools/pipelines/templates/include-publish-npm-package-steps.yml
--- a/tools/pipelines/templates/include-publish-npm-package-steps.yml
+++ b/tools/pipelines/templates/include-publish-npm-package-steps.yml
@@ -44,6 +44,7 @@ steps:
           echo "@fluid-experimental:registry=${{ parameters.feedName }}" >> ./.npmrc
           echo "@fluid-tools:registry=${{ parameters.feedName }}" >> ./.npmrc
           echo "always-auth=true" >> ./.npmrc
+          echo "official=false" >> ./.npmrc
           cat .npmrc
       ${{ if eq(parameters.official, true) }}:
         script: |
@@ -52,6 +53,7 @@ steps:
           echo "@fluid-experimental:registry=${{ parameters.feedName }}" >> ./.npmrc
           echo "@fluid-tools:registry=${{ parameters.feedName }}" >> ./.npmrc
           echo "always-auth=true" >> ./.npmrc
+          echo "official=true" >> ./.npmrc
           cat .npmrc
           echo Deleting @fluid-internal packages
           rm -f fluid-internal-*
@@ -144,23 +146,27 @@ steps:
               rm publish_log
               break
             fi
-            # packageVersion=$(grep -oP 'npm notice : \K.*' publish_log)
-            # echo "publish_log"
-            # echo cat publish_log
-            # echo "packageVersion"
-            # echo $packageVersion
-            # rm publish_log
-            # az rest --method patch --uri https://pkgs.dev.azure.com/fluidframework/_apis/packaging/feeds/testRishhiRetentionPolicy/npm/$packageName/versions/$packageVersion?api-version=7.1-preview.1 --body '{
-            #   "views": {
-            #     "op": "add",
-            #     "path": "/views/-",
-            #     "value": "Release"
-            #   }
-            # }'
-            # if [ $? -ne 0 ]; then
-            #   echo "Failed to promote package to Release view"
-            #   exit 1
-            # fi
+            rm publish_log
+            packageVersion=$(grep -oP 'npm notice : \K.*' publish_log)
+            echo "publish_log"
+            echo cat publish_log
+            echo "packageVersion"
+            echo $packageVersion
+            echo "official"
+            official=$(npm config get official)
+            echo $official
+            rm publish_log
+            az rest --method patch --uri https://pkgs.dev.azure.com/fluidframework/_apis/packaging/feeds/testRishhiRetentionPolicy/npm/$packageName/versions/$packageVersion?api-version=7.1-preview.1 --body '{
+              "views": {
+                "op": "add",
+                "path": "/views/-",
+                "value": "Release"
+              }
+            }'
+            if [ $? -ne 0 ]; then
+              echo "Failed to promote package to Release view"
+              exit 1
+            fi
           done
         fi
       done
