test network connection

diff --git a/tools/pipelines/templates/include-publish-npm-package-steps.yml b/tools/pipelines/templates/include-publish-npm-package-steps.yml
--- a/tools/pipelines/templates/include-publish-npm-package-steps.yml
+++ b/tools/pipelines/templates/include-publish-npm-package-steps.yml
@@ -107,50 +107,59 @@ steps:
           do
             npm publish $f $tag ${{ parameters.publishFlags }} 2>&1 | tee publish_log
 
-            if [ $errorFlag == 0 ];
+            checkError=$(npx npm-return-error-msg)
+
+            if [[ $checkError =~ "NPM ERR! code ENOTFOUND"]]
             then
-              echo "Check ERROR MSG! BEFORE"
-              npx npm-return-error-msg
+              echo "Check ERROR MSG! AFTER"
+              if ! $i -eq $maximumRetryIfNetworkError
+              then
+                echo "Network Error Detected"
+                continue
+              else
+                echo "Final Network Error"
+                exit 1
+              fi
             fi
 
-            if grep -q "npm ERR!" "publish_log"
-            then
-                echo "Check ERROR MSG! AFTER"
-                if grep -q "code ENOTFOUND" "publish_log"
-                then
-                  if ! $i -eq $maximumRetryIfNetworkError
-                  then
-                    echo "Network Error Detected"
-                    continue
-                  else
-                    echo "Final Network Error"
-                    exit 1
-                  fi
-                else
-                  if grep -q "You cannot publish over the previously published versions" "publish_log"
-                  then
-                    echo Package has already been published.
-                    local_f="${f}_local"
-                    mv "$f" "$local_f"
-                    package_name=$(grep -oP 'npm notice package: \K.*' "publish_log")
-                    npm pack $package_name
-                    if cmp -s "$f" "$local_f"
-                    then
-                      echo Continuing as published package matches the current one that was attempting to be released.
-                      continue
-                    else
-                      echo ERROR: Published package does not match the current one attempting to be released for the same version.
-                    fi
-                  fi
-                  rm "$f"
-                  mv "$local_f" "$f"
-                  exit 1
-                fi
-            else
-              rm publish_log
-              break
-            fi
-            rm publish_log
+            # if grep -q "npm ERR!" "publish_log"
+            # then
+            #     echo "Check ERROR MSG! AFTER"
+            #     if grep -q "code ENOTFOUND" "publish_log"
+            #     then
+            #       if ! $i -eq $maximumRetryIfNetworkError
+            #       then
+            #         echo "Network Error Detected"
+            #         continue
+            #       else
+            #         echo "Final Network Error"
+            #         exit 1
+            #       fi
+            #     else
+            #       if grep -q "You cannot publish over the previously published versions" "publish_log"
+            #       then
+            #         echo Package has already been published.
+            #         local_f="${f}_local"
+            #         mv "$f" "$local_f"
+            #         package_name=$(grep -oP 'npm notice package: \K.*' "publish_log")
+            #         npm pack $package_name
+            #         if cmp -s "$f" "$local_f"
+            #         then
+            #           echo Continuing as published package matches the current one that was attempting to be released.
+            #           continue
+            #         else
+            #           echo ERROR: Published package does not match the current one attempting to be released for the same version.
+            #         fi
+            #       fi
+            #       rm "$f"
+            #       mv "$local_f" "$f"
+            #       exit 1
+            #     fi
+            # else
+            #   rm publish_log
+            #   break
+            # fi
+            # rm publish_log
           done
         fi
         let errorFlag+=1
