promotion only if internal

diff --git a/tools/pipelines/templates/include-publish-npm-package-steps.yml b/tools/pipelines/templates/include-publish-npm-package-steps.yml
--- a/tools/pipelines/templates/include-publish-npm-package-steps.yml
+++ b/tools/pipelines/templates/include-publish-npm-package-steps.yml
@@ -155,16 +155,18 @@ steps:
             official=$(npm config get official)
             echo $official
             rm publish_log
-            az rest --method patch --uri https://pkgs.dev.azure.com/fluidframework/_apis/packaging/feeds/testRishhiRetentionPolicy/npm/$packageName/versions/$packageVersion?api-version=7.1-preview.1 --body '{
-              "views": {
-                "op": "add",
-                "path": "/views/-",
-                "value": "Release"
-              }
-            }'
-            if [ $? -ne 0 ]; then
-              echo "Failed to promote package to Release view"
-              exit 1
+            if [ "$official" = false ]; then
+              az rest --method patch --uri https://pkgs.dev.azure.com/fluidframework/_apis/packaging/feeds/testRishhiRetentionPolicy/npm/$packageName/versions/$packageVersion?api-version=7.1-preview.1 --body '{
+                "views": {
+                  "op": "add",
+                  "path": "/views/-",
+                  "value": "Release"
+                }
+              }'
+              if [ $? -ne 0 ]; then
+                echo "Failed to promote package to Release view"
+                exit 1
+              fi
             fi
           done
         fi
