lts: Fix stress tests runs (#26096)
## Description

For a while, the runs of the stress tests pipeline in the LTS branch
have been broken for different reasons. This PR addresses them all so we
can continue running that pipeline for the LTS branch.

Main changes:

- Bring in the template file that configures our centralized ADO feed to
download dependencies.
- Replace the Npm tasks with Bash tasks that use pnpm. Npm tasks don't
respect the configuration done by the previous bullet point.
- Fix path for package in the artifact (we replaced `scoped/unscoped`
with `tarballs` in build-tools a while back).
- Pin the dependency on an internal package (oteljs) to a version that
doesn't cause issues in our LTS branch, where ESM vs CJS is not cleaned
up like in main.
- Update Node from 20.15.1 to 20.19.0 to match main (and we know it
fixes a couple of issues with module resolution).

Fixes
[AB#54754](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/54754)
and
[AB#54755](https://dev.azure.com/fluidframework/235294da-091d-4c29-84fc-cdfc3d90890b/_workitems/edit/54755),
plus some other issues hiding behind those.

diff --git a/tools/pipelines/templates/include-test-real-service.yml b/tools/pipelines/templates/include-test-real-service.yml
--- a/tools/pipelines/templates/include-test-real-service.yml
+++ b/tools/pipelines/templates/include-test-real-service.yml
@@ -57,6 +57,7 @@ jobs:
       pool: ${{ parameters.poolBuild }}
       timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
       variables:
+      - group: ado-feeds
       # We use 'chalk' to colorize output, which auto-detects color support in the
       # running terminal.  The log output shown in Azure DevOps job runs only has
       # basic ANSI color support though, so force that in the pipeline
@@ -67,7 +68,7 @@ jobs:
       - name: testPackageFilePattern
         value: ${{ replace(replace(parameters.testPackage, '@', '' ), '/', '-') }}-*.tgz
       - name: testPackagePathPattern
-        value: $(Pipeline.Workspace)/client/pack/scoped/${{ variables.testPackageFilePattern }}
+        value: $(Pipeline.Workspace)/client/pack/tarballs/${{ variables.testPackageFilePattern }}
       - name: skipComponentGovernanceDetection
         value: true
       - ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/test/') }}:
@@ -129,16 +130,15 @@ jobs:
 
       # Install
       - task: UseNode@1
-        displayName: Use Node 20.15.1
+        displayName: Use Node 20.19.0
         inputs:
-          version: 20.15.1
-      - task: Npm@1
-        displayName: Install npm 10
-        retryCountOnTaskFailure: 4
-        inputs:
-          command: 'custom'
-          customCommand: 'install --global npm@^10'
-          customRegistry: 'useNpmrc'
+          version: 20.19.0
+
+      - template: /tools/pipelines/templates/include-install-pnpm.yml@self
+        parameters:
+          buildDirectory: $(Pipeline.Workspace)
+
+      - template: /tools/pipelines/templates/include-setup-npmrc-for-download.yml@self
 
       # Download artifact
       - task: DownloadPipelineArtifact@2
@@ -169,21 +169,7 @@ jobs:
           targetType: 'inline'
           workingDirectory: ${{ parameters.testWorkspace }}
           script: |
-            echo Initialize package
-            npm init --yes
-
-            echo Generating .npmrc
-            echo "registry=https://registry.npmjs.org" >> ./.npmrc
-            echo "always-auth=false" >> ./.npmrc
-
-            echo "@fluidframework:registry=${{ variables.feed }}" >> ./.npmrc
-            echo "@fluid-experimental:registry=${{ variables.feed }}" >> ./.npmrc
-            echo "@fluid-internal:registry=${{ variables.feed }}" >> ./.npmrc
-            echo "@ff-internal:registry=https://pkgs.dev.azure.com/fluidframework/internal/_packaging/build/npm/registry/" >> ./.npmrc
-            echo "@microsoft:registry=https://pkgs.dev.azure.com/fluidframework/internal/_packaging/office/npm/registry/" >> ./.npmrc
-            echo "always-auth=true" >> ./.npmrc
-            cat .npmrc
-
+            set -eu -o pipefail
             if [[ `ls -1 ${{ variables.testPackagePathPattern }} | wc -l` -eq 1 ]]; then
               echo "##vso[task.setvariable variable=testPackageTgz;isOutput=true]`ls ${{ variables.testPackagePathPattern }}`"
             else
@@ -191,21 +177,43 @@ jobs:
               echo "##vso[task.logissue type=error]Test package '${{ parameters.testPackage }}' not found, or there are more then one found"
             fi
 
-      # Auth to internal feed
-      - task: npmAuthenticate@0
-        displayName: 'npm authenticate (internal feed)'
+
+      # Pin oteljs to a version that doesn't depend on packages that cause issues in our LTS branch
+      # because they expect everything to be ESM, which we're not using yet in LTS (we probably can't make such a big
+      # change to how the packages work in LTS, it would almost certainly result in some breaking changes).
+      # Note that it needs to be done before running `pnpm install` so that the override is respected during installation.
+      - task: Bash@3
+        displayName: 'Add pnpm override for @microsoft/oteljs@4.20.30'
         inputs:
-          workingFile: ${{ parameters.testWorkspace }}/.npmrc
+          targetType: 'inline'
+          workingDirectory: ${{ parameters.testWorkspace }}
+          script: |
+            # Init first so package.json exists.
+            pnpm init
+            # Apply override
+            node -e "
+            const fs = require('fs');
+            const pkgPath = './package.json';
+            const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
+            pkg.pnpm = pkg.pnpm || {};
+            pkg.pnpm.overrides = pkg.pnpm.overrides || {};
+            pkg.pnpm.overrides['@microsoft/oteljs'] = '4.20.30';
+            fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2));
+            "
 
       # Install test and logger package
-      - task: Npm@1
-        displayName: 'npm install'
-        retryCountOnTaskFailure: 4
+      # Use a Bash@3 task instead of Npm@1 so we can use pnpm, which will respect the .npmrc file configured globally earlier
+      - task: Bash@3
+        displayName: 'pnpm install'
+        # ADO feeds have latency on the order of minutes before packages are available downstream. See:
+        # https://learn.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops#upstream-sources-health-status
+        # This pipeline installs packages which were published very recently relative to its runtime, hence the rather high retry count here.
+        retryCountOnTaskFailure: 10
         inputs:
-          command: 'custom'
-          workingDir: ${{ parameters.testWorkspace }}
-          customCommand: 'install $(Initialize.testPackageTgz) @ff-internal/aria-logger'
-          customRegistry: 'useNpmrc'
+          targetType: 'inline'
+          workingDirectory: ${{ parameters.testWorkspace }}
+          script: |
+            pnpm install $(Initialize.testPackageTgz) @ff-internal/aria-logger
 
       # Download Test Files & Install Extra Dependencies
       # These steps are intended to include extra dependencies that are not available as
@@ -238,14 +246,14 @@ jobs:
 
         - ${{ if ne(parameters.extraDependencies, 'null') }}:
           # Install extra dependencies for test files
-          - task: Npm@1
-            displayName: 'npm install - extra dependencies for test files'
+          # Use a Bash@3 task instead of Npm@1 so we can use pnpm, which will respect the .npmrc file configured globally earlier
+          - task: Bash@3
+            displayName: 'pnpm install - extra dependencies for test files'
             retryCountOnTaskFailure: 4
             inputs:
-              command: 'custom'
-              workingDir: ${{ parameters.testWorkspace }}
-              customCommand: 'install ${{ parameters.extraDependencies }}'
-              customRegistry: 'useNpmrc'
+              targetType: 'inline'
+              workingDirectory: ${{ parameters.testWorkspace }}
+              script: 'pnpm install ${{ parameters.extraDependencies }}'
 
       # run the test
       - task: Npm@1
