test

diff --git a/tools/pipelines/templates/include-set-package-version.yml b/tools/pipelines/templates/include-set-package-version.yml
--- a/tools/pipelines/templates/include-set-package-version.yml
+++ b/tools/pipelines/templates/include-set-package-version.yml
@@ -184,6 +184,8 @@ steps:
     targetType: 'inline'
     workingDirectory: ${{ parameters.buildDirectory }}
     script: |
-      # grep returns 0 if there are matches, but we want to return 1 if there are matches, so we negate the grep
-      # command result
-      ! grep -r "\^2.0.0-internal.\d*.\d*.\d*" ./**/package.json
+      grep -r -e"\^2.0.0-internal.\d*.\d*.\d*" `find . -type d -name node_modules -prune -o -name 'package.json' -print`
+      if [[ $? == 0 ]]; then
+        echo "##vso[task.logissue type=error]Fluid internal versions shouldn't use caret dependencies"
+        exit -1;
+      fi
