check network error

diff --git a/tools/pipelines/templates/include-publish-npm-package-steps.yml b/tools/pipelines/templates/include-publish-npm-package-steps.yml
--- a/tools/pipelines/templates/include-publish-npm-package-steps.yml
+++ b/tools/pipelines/templates/include-publish-npm-package-steps.yml
@@ -111,18 +111,17 @@ steps:
 
             echo "CHECK ERROR : " $checkError
 
-            # if [[ "$checkError" =~ "NPM ERR! code ENOTFOUND"]]
-            # then
-            #   echo "Check ERROR MSG! AFTER"
-            #   if ! $i -eq $maximumRetryIfNetworkError
-            #   then
-            #     echo "Network Error Detected"
-            #     continue
-            #   else
-            #     echo "Final Network Error"
-            #     exit 1
-            #   fi
-            # fi
+            if [ "$checkError" = "NPM ERR! code ENOTFOUND" ]; then
+              echo "Check Error! After!"
+              if ! $i -eq $maximumRetryIfNetworkError
+              then
+                echo "Network Error Detected"
+                continue
+              else
+                echo "Final Network Error"
+                exit 1
+              fi
+            fi
 
             # if grep -q "npm ERR!" "publish_log"
             # then
