Always run both types of tests

diff --git a/tools/pipelines/test-perf-benchmarks.yml b/tools/pipelines/test-perf-benchmarks.yml
--- a/tools/pipelines/test-perf-benchmarks.yml
+++ b/tools/pipelines/test-perf-benchmarks.yml
@@ -431,21 +431,36 @@ stages:
               cp ${{ variables.testWorkspace }}/.npmrc . ;
               npm i ;
 
+        # We run both types of tests in the same bash step so we can make sure to run the second set even if the first
+        # one fails.
+        # Doing this with separate ADO steps is not easy.
+        # This step reports failure if either of the test runs reports failure.
         - task: Bash@3
-          displayName: Run execution time tests
+          displayName: Run tests
           inputs:
             targetType: 'inline'
             workingDirectory: ${{ variables.testWorkspace }}/node_modules/${{ variables.testPackage }}
             script: |
-              npm run test:benchmark:report;
 
-        - task: Bash@3
-          displayName: Run memory usage tests
-          inputs:
-            targetType: 'inline'
-            workingDirectory: ${{ variables.testWorkspace }}/node_modules/${{ variables.testPackage }}
-            script: |
+              # Run execution time tests
+              npm run test:benchmark:report;
+              executionTimeTestsExitCode=$?;
+
+              # Run memory tests
               npm run test:memory-profiling:report;
+              memoryTestsExitCode=$?;
+
+              if [[ $executionTimeTestsExitCode -ne 0 ]]; then
+                echo "##vso[task.logissue type=error]Exit code for runtime tests execution = $executionTimeTestsExitCode"
+              fi
+
+              if [[ $memoryTestsExitCode -ne 0]]; then
+                echo "##vso[task.logissue type=error]Exit code for memory tests execution = $memoryTestsExitCode"
+              fi
+
+              if [[ $executionTimeTestsExitCode -ne 0 ]] || [[ $memoryTestsExitCode -ne 0 ]]; then
+                exit 1;
+              fi
 
         - task: Bash@3
           displayName: Write measurements to Aria/Kusto - execution time
