use latest if SHA-based DL fails

diff --git a/.github/workflows/azure-static-web-apps-polite-pebble-004dbbb10.yml b/.github/workflows/azure-static-web-apps-polite-pebble-004dbbb10.yml
--- a/.github/workflows/azure-static-web-apps-polite-pebble-004dbbb10.yml
+++ b/.github/workflows/azure-static-web-apps-polite-pebble-004dbbb10.yml
@@ -25,9 +25,13 @@ jobs:
       - name: Download and extract api-extractor JSON
         id: docs-json
         run: |
-          wget https://fluidframework.z19.web.core.windows.net/${{ github.sha }}.tar.gz
+          wget -q https://fluidframework.z19.web.core.windows.net/${{ github.sha }}.tar.gz -O api-extractor.tar.gz
+          if [ $? -ne 0 ]; then
+            wget -q https://fluidframework.z19.web.core.windows.net/latest.tar.gz -O api-extractor.tar.gz
+            echo "${{ github.sha }}.tar.gz not found; downloading latest.tar.gz"
+          fi
           mkdir -p ./_api-extractor-temp/doc-models/
-          tar -C ./_api-extractor-temp/doc-models/ -zxvf ${{ github.sha }}.tar.gz
+          tar -C ./_api-extractor-temp/doc-models/ -zxvf api-extractor.tar.gz
       - name: npm run build:mdapidocs
         id: mdapidocs
         run: |
